# co## Launch the client
Open a terminal in the root of the project

```sh
go run public/apiRest.go
```
contrl + c   -->  to end


## Import Postman

https://www.getpostman.com/collections/384b3516af0c95659385nfig.yaml

logs:
  level: info
  path: logs/
  max_size: 1
  max_backups: 1
  max_age: 1
server:
  port: :8000
data:
    data_type: csv
  # csv o json
